# GoReleaser configuration for Bazaruto Insurance Platform
# https://goreleaser.com/

project_name: bazaruto

before:
  hooks:
    - go mod tidy
    - go mod verify
    - go vet ./...
    - go test -short ./...

builds:
  - id: bazarutod
    binary: bazarutod
    main: ./cmd/bazarutod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/edsonmichaque/bazaruto/internal/version.Version={{.Version}}
      - -X github.com/edsonmichaque/bazaruto/internal/version.Commit={{.Commit}}
      - -X github.com/edsonmichaque/bazaruto/internal/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: bazarutod
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config.yaml.example
      - config/business_rules.json.example
      - README.md
      - LICENSE
      - docs/

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

dockers:
  - image_templates:
      - "bazaruto:{{ .Version }}"
      - "bazaruto:latest"
    dockerfile: build/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --platform=linux/arm64
    extra_files:
      - config.yaml.example
      - config/business_rules.json.example

nfpms:
  - id: bazarutod
    package_name: bazarutod
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    description: "Bazaruto Insurance Platform - Backend service for insurance product marketplace"
    homepage: "https://github.com/edsonmichaque/bazaruto"
    maintainer: "Bazaruto Team <team@bazaruto.com>"
    vendor: "Bazaruto"
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - src: config.yaml.example
        dst: /etc/bazaruto/config.yaml.example
      - src: config/business_rules.json.example
        dst: /etc/bazaruto/business_rules.json.example
      - src: README.md
        dst: /usr/share/doc/bazaruto/README.md
      - src: LICENSE
        dst: /usr/share/doc/bazaruto/LICENSE
      - src: docs/
        dst: /usr/share/doc/bazaruto/
      - dst: /var/lib/bazaruto
        type: dir
      - dst: /var/log/bazaruto
        type: dir
      - dst: /var/cache/bazaruto
        type: dir
      - dst: /etc/bazaruto
        type: dir
    scripts:
      preinstall: packaging/scripts/preinstall.sh
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh
      postremove: packaging/scripts/postremove.sh

release:
  github:
    owner: edsonmichaque
    name: bazaruto
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
  header: |
    ## What's Changed

    Full Changelog: https://github.com/edsonmichaque/bazaruto/compare/{{ .PreviousTag }}...{{ .Tag }}
