server:
  addr: ":8080"
  read_timeout: 30s
  write_timeout: 60s
  idle_timeout: 90s

db:
  dsn: "postgres://postgres:postgres@localhost:5432/bazaruto?sslmode=disable"
  max_connections: 25
  min_connections: 5
  connect_timeout: 5s
  acquire_timeout: 3s
  max_lifetime: 30m
  idle_timeout: 10m

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  dial_timeout: 2s
  read_timeout: 1s
  write_timeout: 1s

rate:
  enabled: true
  provider: redis  # "redis" or "memory"
  per_minute: 120
  burst: 30
  key_strategy: ip
  key_prefix: "rl:"
  ttl: 10m
  gc_interval: 5m
  
  policies:
    - name: quotes-write
      match:
        path_prefix: /v1/quotes
        methods: [POST]
      limits:
        - scope: global
          per_minute: 300
          burst: 60
        - scope: header
          header: X-API-Key
          per_minute: 120
          burst: 30
    - name: policies-read
      match:
        path_prefix: /v1/policies
        methods: [GET]
      limits:
        - scope: global
          per_minute: 1000
          burst: 200

observability:
  log:
    level: info
    format: json
  metrics:
    enabled: true
    path: /metrics
  tracing:
    enabled: true
    endpoint: "localhost:4317"
    service_name: bazaruto
