# Development Environment Configuration
# This configuration is optimized for local development

server:
  addr: ":8080"
  read_timeout: 30s
  write_timeout: 60s
  idle_timeout: 90s

# SQLite database for development
db:
  dsn: "file:./bazaruto_dev.db?cache=shared&mode=rwc"
  max_connections: 10
  min_connections: 2
  connect_timeout: 5s
  acquire_timeout: 3s
  max_lifetime: 30m
  idle_timeout: 10m

# Redis not required for development
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  dial_timeout: 2s
  read_timeout: 1s
  write_timeout: 1s

# Relaxed rate limiting for development
rate:
  enabled: true
  provider: memory
  per_minute: 1000
  burst: 200
  key_strategy: ip
  key_prefix: "rl:"
  ttl: 10m
  gc_interval: 5m

# Development observability settings
observability:
  log:
    level: debug
    format: text
  metrics:
    enabled: true
    path: /metrics
  tracing:
    enabled: false
    endpoint: "localhost:4317"
    service_name: bazaruto-dev

# Email disabled for development
email:
  enabled: false
  provider: smtp
  smtp:
    host: "localhost"
    port: 1025
    username: ""
    password: ""
    from: "dev@bazaruto.local"
    tls: false

# Webhooks enabled for testing
webhooks:
  enabled: true
  timeout: 30s
  max_retries: 3
  retry_delay: 5s

# Relaxed security for development
security:
  cors:
    enabled: true
    origins: ["*"]
    methods: ["*"]
    headers: ["*"]
    credentials: false
  csrf:
    enabled: false
    secret: "dev-secret"
